### ISSUE TITLE
mvn Package Build Failure

### ISSUE THREAD

**Issue by gspeiliu** [intersimone999/acryl#3]
$ mvn package

[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< it.unimol:ACRyL >---------------------------
[INFO] Building ACRyL 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.393 s
[INFO] Finished at: 2021-12-12T14:21:29+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ACRyL: Could not resolve dependencies for project it.unimol:ACRyL:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.gradle:gradle-core:jar:4.2.1: Failed to read artifact descriptor for org.gradle:gradle-core:jar:4.2.1: Could not transfer artifact org.gradle:gradle-core:pom:4.2.1 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [Spring Source Libs (http://repo.springsource.org/libs-release-remote/, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by intersimone999** [comment]
Thanks, fixed in commit 52738521becd15ddf99df6d2f83f652f02831247; that was, actually, a useless dependency, so I just removed it.
